"""empty message

Revision ID: 29729bc6c4f7
Revises: 
Create Date: 2021-07-11 11:21:33.864805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29729bc6c4f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('dre', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno')
    # ### end Alembic commands ###
